# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\x12\x05notes\"^\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"7\n\x11\x43reateNoteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"/\n\x12\x43reateNoteResponse\x12\x19\n\x04note\x18\x01 \x01(\x0b\x32\x0b.notes.Note\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x0fGetNoteResponse\x12\x19\n\x04note\x18\x01 \x01(\x0b\x32\x0b.notes.Note\"\x12\n\x10ListNotesRequest\"/\n\x11ListNotesResponse\x12\x1a\n\x05notes\x18\x01 \x03(\x0b\x32\x0b.notes.Note\"?\n\x1cUpdateNoteDescriptionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\":\n\x1dUpdateNoteDescriptionResponse\x12\x19\n\x04note\x18\x01 \x01(\x0b\x32\x0b.notes.Note\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteNoteResponse\"\x0f\n\rHealthRequest\"\x10\n\x0eHealthResponse2\xa9\x03\n\x0cNotesService\x12\x41\n\nCreateNote\x12\x18.notes.CreateNoteRequest\x1a\x19.notes.CreateNoteResponse\x12\x38\n\x07GetNote\x12\x15.notes.GetNoteRequest\x1a\x16.notes.GetNoteResponse\x12>\n\tListNotes\x12\x17.notes.ListNotesRequest\x1a\x18.notes.ListNotesResponse\x12\x62\n\x15UpdateNoteDescription\x12#.notes.UpdateNoteDescriptionRequest\x1a$.notes.UpdateNoteDescriptionResponse\x12\x41\n\nDeleteNote\x12\x18.notes.DeleteNoteRequest\x1a\x19.notes.DeleteNoteResponse\x12\x35\n\x06Health\x12\x14.notes.HealthRequest\x1a\x15.notes.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=22
  _globals['_NOTE']._serialized_end=116
  _globals['_CREATENOTEREQUEST']._serialized_start=118
  _globals['_CREATENOTEREQUEST']._serialized_end=173
  _globals['_CREATENOTERESPONSE']._serialized_start=175
  _globals['_CREATENOTERESPONSE']._serialized_end=222
  _globals['_GETNOTEREQUEST']._serialized_start=224
  _globals['_GETNOTEREQUEST']._serialized_end=252
  _globals['_GETNOTERESPONSE']._serialized_start=254
  _globals['_GETNOTERESPONSE']._serialized_end=298
  _globals['_LISTNOTESREQUEST']._serialized_start=300
  _globals['_LISTNOTESREQUEST']._serialized_end=318
  _globals['_LISTNOTESRESPONSE']._serialized_start=320
  _globals['_LISTNOTESRESPONSE']._serialized_end=367
  _globals['_UPDATENOTEDESCRIPTIONREQUEST']._serialized_start=369
  _globals['_UPDATENOTEDESCRIPTIONREQUEST']._serialized_end=432
  _globals['_UPDATENOTEDESCRIPTIONRESPONSE']._serialized_start=434
  _globals['_UPDATENOTEDESCRIPTIONRESPONSE']._serialized_end=492
  _globals['_DELETENOTEREQUEST']._serialized_start=494
  _globals['_DELETENOTEREQUEST']._serialized_end=525
  _globals['_DELETENOTERESPONSE']._serialized_start=527
  _globals['_DELETENOTERESPONSE']._serialized_end=547
  _globals['_HEALTHREQUEST']._serialized_start=549
  _globals['_HEALTHREQUEST']._serialized_end=564
  _globals['_HEALTHRESPONSE']._serialized_start=566
  _globals['_HEALTHRESPONSE']._serialized_end=582
  _globals['_NOTESSERVICE']._serialized_start=585
  _globals['_NOTESSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
